In [4]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from sklearn import linear_model

In [14]:
df = pd.read_csv('https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [8]:
# y = m1x1 + m2x2 + m3x3 + b
import math
bedroom_median = math.floor(df.bedrooms.median())
bedroom_median

4

In [15]:
#data preprocessing
df.bedrooms = df.bedrooms.fillna(bedroom_median)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [16]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms', 'age']], df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [17]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [18]:
reg.intercept_

221323.00186540408

In [19]:
#predict home price of 3000 sq.ft, 3 bed room , 40 years old home
#and 2500 sq.ft, 4 bed room, 5 years old home

In [21]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [22]:
112.06244194*3000 + 23388.88007794 *3 + 40*(-3231.71790863) +221323.00186540408

498408.2515740241

In [23]:
reg.predict([[2500,4,5]])

array([578876.03748933])


# Exercise

This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,

2 yr experience, 9 test score, 6 interview score

12 yr experience, 10 test score, 10 interview score

In [60]:
df1 = pd.read_csv('https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/Exercise/hiring.csv')
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [26]:
!pip install word2number

  Stored in directory: /home/dsxuser/.cache/pip/wheels/46/2f/53/5f5c1d275492f2fce1cdab9a9bb12d49286dead829a4078e0e
Successfully built word2number


In [27]:
from word2number import w2n

In [61]:
df1.experience = df1.experience.fillna('zero')
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [62]:
df1.experience = df1.experience.apply(w2n.word_to_num)
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [64]:
mean_textscore = math.floor(df1['test_score(out of 10)'].mean())
df1['test_score(out of 10)'] = df1['test_score(out of 10)'].fillna(mean_textscore)
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [66]:
reg1 = linear_model.LinearRegression()
reg1.fit(df1[['experience', 'test_score(out of 10)','interview_score(out of 10)']], df1[['salary($)']])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [69]:
reg1.predict([[2,9,6]])

array([[53713.86677124]])

In [70]:
reg1.predict([[12,10,10]])

array([[93747.79628651]])

In [71]:
reg1.coef_

array([[2922.26901502, 2221.30909959, 2147.48256637]])

In [73]:
reg1.intercept_

array([14992.65144669])

In [75]:
2922.26901502*2 + 2221.30909959*9 + 2147.48256637*6 +14992.65144669

53713.86677126

In [76]:
2922.26901502*12 + 2221.30909959*10 + 2147.48256637*10 +14992.65144669

93747.79628653